#!/usr/bin/env bash
# setup_addresses.sh — Create and fund N+1 addresses.
# Usage: bash scripts/setup_addresses.sh <N>
# Creates N sensor addresses + 1 window-closer address.
# Writes addresses and key aliases to .env (do NOT commit .env).

set -euo pipefail

N=${1:-32}
TOTAL=$((N + 1))
ENV_FILE=".env"

echo "Creating $TOTAL addresses (${N} sensors + 1 window-closer)..."

# Ensure we are on localnet
iota client switch --env localnet

# Create addresses
ADDRESSES=()
for i in $(seq 1 "$TOTAL"); do
    ADDR=$(iota client new-address ed25519 2>&1 | grep -oE '0x[0-9a-f]{64}' | head -1)
    echo "  Created address $i: $ADDR"
    ADDRESSES+=("$ADDR")
done

# Fund all addresses from faucet
echo "Funding addresses from faucet..."
for ADDR in "${ADDRESSES[@]}"; do
    iota client faucet --address "$ADDR" --url http://127.0.0.1:9123 || true
    sleep 0.2
done

# Write to .env
{
    echo "# Auto-generated by setup_addresses.sh — DO NOT COMMIT"
    echo "IOTA_ENV=localnet"
    for i in "${!ADDRESSES[@]}"; do
        if [ "$i" -lt "$N" ]; then
            echo "SENSOR_ADDRESS_$((i+1))=${ADDRESSES[$i]}"
        else
            echo "CLOSER_ADDRESS=${ADDRESSES[$i]}"
        fi
    done
} > "$ENV_FILE"

echo "Addresses written to $ENV_FILE"
echo "Done. Verify balances with: iota client balance"
